name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "PHP ${{ matrix.php }}"
        strategy:
            fail-fast: false
            matrix:
                php: ["7.3", "7.4", "8.0"]

        steps:
            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -
                name: Install dependencies
                run: composer update

            -
                name: Composer validate
                run: composer validate --strict --ansi

            -
                name: Run Psalm
                run: vendor/bin/psalm src --no-progress

            -
                name: Run tests
                run: vendor/bin/behat -f progress --strict -vvv --no-interaction --colors
